# Generated by Django 5.1.7 on 2025-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='', verbose_name='Content of the news'),
        ),
    ]
